name: pr

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - **/*.md
      - **/*.gitignore
      - .github/**
      - ty√∂tuntikirjanpito.md
      - backend/Makefile

env:
  GO_VERSION: 1.25.6
  ALPINE_VERSION: 3.23
  BUN_VERSION: 1.3.8

jobs:
  test:
    uses: ./.github/workflows/tests.yaml
    with:
      go-version: ${{ env.GO_VERSION }}
